version: "3.8"

services:
  db:
    container_name: poke-api-go
    image: postgres:16.0-alpine3.18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pokedb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local