DROP TABLE IF EXISTS TRA_TRAINERS;
DROP TABLE IF EXISTS TRA_ROLES;
DROP TABLE IF EXISTS TRA_ROLE_MEMBERS;

CREATE TABLE TRA_TRAINERS (
        ID UUID DEFAULT gen_random_uuid () PRIMARY KEY,
        NAME VARCHAR(255) NOT NULL,
        LEVEL INTEGER DEFAULT(1) NOT NULL,
        TEAM VARCHAR(16) DEFAULT 'NONE' NOT NULL,
        AVATARURL VARCHAR(4096),
        FRIENDCODE VARCHAR(32) NOT NULL,
        EMAIL VARCHAR(512) NOT NULL,
        PASSWORD VARCHAR(512) NOT NULL,
        ROLES VARCHAR(32) NOT NULL
    );

CREATE TABLE TRA_ROLES (
        ID BIGSERIAL PRIMARY KEY,
        NAME VARCHAR(255) NOT NULL
    );

INSERT INTO TRA_ROLES(NAME) VALUES
('ADMIN'),
('USER');

CREATE TABLE TRA_ROLE_MEMBERS (
        ID BIGSERIAL PRIMARY KEY,
        TRAINERID UUID NOT NULL,
        ROLEID BIGSERIAL NOT NULL
    );