DROP TABLE IF EXISTS POK_POKEMONS;

CREATE TABLE POK_POKEMONS (
        ID UUID DEFAULT gen_random_uuid () PRIMARY KEY,
        POKEDEXID INTEGER NOT NULL,
        GENERATIONID INTEGER NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        VARIANT VARCHAR(255),
        TYPEONE VARCHAR(255) DEFAULT 'NONE' NOT NULL,
        TYPETWO VARCHAR(255) DEFAULT 'NONE' NOT NULL,
        RARITY VARCHAR(255) DEFAULT 'STANDARD' NOT NULL,
        AVAILABLE BOOLEAN DEFAULT 'false' NOT NULL,
        SHINY BOOLEAN DEFAULT 'false' NOT NULL,
        MEGA BOOLEAN DEFAULT 'false' NOT NULL,
        MEGAFAMILY BOOLEAN DEFAULT 'false' NOT NULL,
        SHADOW BOOLEAN DEFAULT 'false' NOT NULL,
        TRADEEVOLVE BOOLEAN DEFAULT 'false' NOT NULL,
        TRADEEVOLVEFAMILY BOOLEAN DEFAULT 'false' NOT NULL,
        TRADEABLE BOOLEAN DEFAULT 'false' NOT NULL,
        RAIDABLE BOOLEAN DEFAULT 'false' NOT NULL,
        ALTERNATEFORM BOOLEAN DEFAULT 'false' NOT NULL,
        COSTUMEFORM BOOLEAN DEFAULT 'false' NOT NULL,
        VISIBLE BOOLEAN DEFAULT 'false' NOT NULL
    );